// build.js - Simple build script with no external dependencies
const fs = require('fs');

console.log('🚀 Starting build process...');

// Get the measurement ID from environment variables
const measurementId = process.env.GA_MEASUREMENT_ID;

if (!measurementId) {
    console.warn('⚠️  Warning: GA_MEASUREMENT_ID not found in environment variables');
    console.log('   Creating config with placeholder...');
    
    // Create config with placeholder
    const configContent = `// config.js - Generated by build process
window.APP_CONFIG = {
    GA_MEASUREMENT_ID: null, // No measurement ID - analytics disabled
    APP_VERSION: '1.0.0',
    DEBUG_MODE: false
};`;
    
    fs.writeFileSync('config.js', configContent);
    console.log('📝 Created config.js with analytics disabled');
} else {
    console.log('✅ GA_MEASUREMENT_ID found, creating config...');
    
    // Create config with real measurement ID
    const configContent = `// config.js - Generated by build process
window.APP_CONFIG = {
    GA_MEASUREMENT_ID: '${measurementId}',
    APP_VERSION: '1.0.0',
    DEBUG_MODE: false
};`;
    
    fs.writeFileSync('config.js', configContent);
    console.log('✅ Created config.js with measurement ID');
}

console.log('🎉 Build process completed successfully!');